-- Create Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) NOT NULL,
    vehicle_id BIGINT NOT NULL, -- Logical reference to bikes/cars/scooty id
    vehicle_type TEXT NOT NULL, -- 'bikes', 'cars', 'scooty'
    rating NUMERIC(2, 1) NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    photos TEXT[], -- Array of image URLs
    is_verified_purchase BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_reviews_vehicle ON public.reviews(vehicle_type, vehicle_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON public.reviews(user_id);

-- Enable RLS
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Policies
-- Anyone can read reviews
CREATE POLICY "Public reviews are viewable by everyone" 
ON public.reviews FOR SELECT 
USING (true);

-- NOTE: Write permissions are handled by the backend (Service Role) which bypasses RLS.
-- We do not add INSERT/UPDATE policies here to avoid type mismatch issues with auth.uid().
